import { create } from 'zustand';
import type { CategoriesStoreState } from './CategoryInterface';

export const useCategoriesStore = create<CategoriesStoreState>(() => ({
  categoriesGroup: [
    {
      id: 1,
      categoryID: 'accessories',
      categoryName: 'ACCESSORIES',
      categoryDescription: '',
      categoryImage: '',
      subCategories: [],
      products: [
        {
          id: 1,
          productID: 'paint-brush',
          productName: 'PAINT BRUSH',
          productCode: 'MET-PBRS-2"',
          productDescription: 'PAINT BRUSH-2"',
          productImage: '',
          productColor: ['black', 'white'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 2,
          productID: 'paint-brush',
          productName: 'PAINT BRUSH',
          productCode: 'MET-PBRS-2.5"',
          productDescription: 'PAINT BRUSH-2.5"',
          productImage: '',
          productColor: ['black', 'purple'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 3,
          productID: 'paint-brush',
          productName: 'PAINT BRUSH',
          productCode: 'MET-PBRS-3"',
          productDescription: 'PAINT BRUSH-3"',
          productImage: '',
          productColor: ['black', 'green'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 4,
          productID: 'paint-brush',
          productName: 'PAINT BRUSH',
          productCode: 'MET-PBRS-4"',
          productDescription: 'PAINT BRUSH-4"',
          productImage: '',
          productColor: ['black', 'gray'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 5,
          productID: 'paint-brush',
          productName: 'PAINT BRUSH',
          productCode: 'MET-PBRS-5"',
          productDescription: 'PAINT BRUSH-5"',
          productImage: '',
          productColor: ['black', 'red'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 6,
          productID: 'paint-brush',
          productName: 'PAINT BRUSH',
          productCode: 'MET-ROLLER BRUSH',
          productDescription: 'PAINT ROLLER BRUSH',
          productImage: '',
          productColor: ['black', 'blue'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 7,
          productID: 'paint-brush',
          productName: 'PAINT BRUSH',
          productCode: 'MET-ROLLER-BRUSH',
          productDescription: 'PAINT ROLLER 4" WITH FRAME',
          productImage: '',
          productColor: ['black', 'orange'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 8,
          productID: 'paint-brush',
          productName: 'PAINT BRUSH',
          productCode: 'TNT-PBRS-ATLAS',
          productDescription: 'PAINT BRUSH-ATLAS 419',
          productImage: '',
          productColor: ['black', 'yellow'],
          prodductSize: ['large', 'medium'],
        },
      ],
    },
    {
      id: 2,
      categoryID: 'glue-and-adhesives',
      categoryName: 'GLUE & ADHESIVES',
      categoryDescription: '',
      categoryImage: '',
      subCategories: [],
      products: [
        {
          id: 1,
          productID: 'tile-glue',
          productName: 'TILE GLUE',
          productCode: 'NPI-TGg',
          productDescription: 'BRITONE TILE ADHESIVE 20KG GREY',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 2,
          productID: 'tile-glue',
          productName: 'TILE GLUE',
          productCode: 'NPI-TGw',
          productDescription: 'BRITONE TILE ADHESIVE 20KG WHITE',
          productImage: '',
          productColor: ['black', 'white'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 3,
          productID: 'wood-glue',
          productName: 'WOOD GLUE',
          productCode: 'NPI-WGg',
          productDescription: 'WOOD GLUE GAL 3,5KG',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 4,
          productID: 'wood-glue',
          productName: 'WOOD GLUE',
          productCode: 'NPI-WG-KG',
          productDescription: 'WOOD GLUE  BARREL',
          productImage: '',
          productColor: ['black', 'white'],
          prodductSize: ['large', 'medium'],
        },
      ],
    },
    {
      id: 3,
      categoryID: 'putty',
      categoryName: 'PUTTY',
      categoryDescription: '',
      categoryImage: '',
      subCategories: [],
      products: [
        {
          id: 1,
          productID: 'ready-mix-putty',
          productName: 'READY MIX PUTTY',
          productCode: 'NPI-PVMd',
          productDescription: 'WALL PUTTY BUCKET',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 2,
          productID: 'ready-mix-putty',
          productName: 'READY MIX PUTTY',
          productCode: 'NPI-PVMg',
          productDescription: 'WALL PUTTY GALLON',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 3,
          productID: 'powder-putty',
          productName: 'POWDER PUTTY',
          productCode: 'NPI-WCP',
          productDescription: 'POWDER PUTTY',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
      ],
    },
    {
      id: 4,
      categoryID: 'epoxy',
      categoryName: 'EPOXY',
      categoryDescription: '',
      categoryImage: '',
      subCategories: [],
      products: [
        {
          id: 1,
          productID: 'clear-coat',
          productName: 'CLEAR COAT',
          productCode: 'NPI-EFPg-100',
          productDescription: 'EPOXY FLOOR PAINT CLEAR COAT',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 2,
          productID: 'primer',
          productName: 'PRIMER',
          productCode: 'NPI-EFPg-200 V',
          productDescription: 'EPOXY FLOOR PAINT 200 V PRIMER',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 3,
          productID: 'primer',
          productName: 'PRIMER',
          productCode: 'NPI-EFPg-474',
          productDescription: 'EPOXY PRIMER 474',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 4,
          productID: 'epoxy-floor-paint',
          productName: 'EPOXY FLOOR PAINT',
          productCode: 'NPI-EFPg-700',
          productDescription: 'EPOXY FLOOR PAINT WHITE 700',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 5,
          productID: 'epoxy-floor-paint',
          productName: 'EPOXY FLOOR PAINT',
          productCode: 'NPI-EFPg-701',
          productDescription: 'EPOXY FLOOR PAINT GREY 701',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 6,
          productID: 'epoxy-floor-paint',
          productName: 'EPOXY FLOOR PAINT',
          productCode: 'NPI-EFPg-710',
          productDescription: 'EPOXY FLOOR PAINT BRICK RED 710',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 7,
          productID: 'epoxy-floor-paint',
          productName: 'EPOXY FLOOR PAINT',
          productCode: 'NPI-EFPg-720',
          productDescription: 'EPOXY FLOOR PAINT YELLOW 720',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 8,
          productID: 'epoxy-floor-paint',
          productName: 'EPOXY FLOOR PAINT',
          productCode: 'NPI-EFPg-730',
          productDescription: 'EPOXY FLOOR PAINT ORANGE 730',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 9,
          productID: 'epoxy-floor-paint',
          productName: 'EPOXY FLOOR PAINT',
          productCode: 'NPI-EFPg-735',
          productDescription: 'EPOXY FLOOR PAINT OCEAN BLUE 735',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 10,
          productID: 'epoxy-floor-paint',
          productName: 'EPOXY FLOOR PAINT',
          productCode: 'NPI-EFPg-750',
          productDescription: 'EPOXY FLOOR PAINT GREEN 750',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 11,
          productID: 'epoxy-floor-paint',
          productName: 'EPOXY FLOOR PAINT',
          productCode: 'NPI-EFPg-770',
          productDescription: 'EPOXY FLOOR PAINT BLACK 770',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 12,
          productID: 'epoxy-putty',
          productName: 'EPOXY PUTTY',
          productCode: 'NPI-EFPg-PUTTY',
          productDescription: 'EPOXY PUTTY GALLON',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 13,
          productID: 'epoxy-zinc-phosphate',
          productName: 'EPOXY ZINC PHOSPHATE',
          productCode: 'NPI-EZPg-700',
          productDescription: 'EPOXY ZINC PHOSPHATE WHITE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 14,
          productID: 'epoxy-zinc-phosphate',
          productName: 'EPOXY ZINC PHOSPHATE',
          productCode: 'NPI-EZPg-740',
          productDescription: 'EPOXY ZINC PHOSPHATE BIEGE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 15,
          productID: 'epoxy-zinc-phosphate',
          productName: 'EPOXY ZINC PHOSPHATE',
          productCode: 'NPI-EZPg-743',
          productDescription: 'EPOXY ZINC PHOSPHATE YELLOW',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 16,
          productID: 'epoxy-zinc-phosphate',
          productName: 'EPOXY ZINC PHOSPHATE',
          productCode: 'NPI-EZPg-750',
          productDescription: 'EPOXY ZINC PHOSPHATE BRICK RED',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 17,
          productID: 'epoxy-zinc-phosphate',
          productName: 'EPOXY ZINC PHOSPHATE',
          productCode: 'NPI-EZPg-765',
          productDescription: 'EPOXY ZINC PHOSPHATE GREY',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 18,
          productID: 'epoxy-zinc-phosphate',
          productName: 'EPOXY ZINC PHOSPHATE',
          productCode: 'NPI-EZPg-770',
          productDescription: 'EPOXY ZINC PHOSPHATE BLACK',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 19,
          productID: 'solvent-free-epoxy',
          productName: 'SOLVENT FREE EPOXY',
          productCode: 'NPI-SFEg-780',
          productDescription: 'SOLVENT FREE EPOXY GAL.780 WHITE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 20,
          productID: 'solvent-free-epoxy',
          productName: 'SOLVENT FREE EPOXY',
          productCode: 'NPI-SFEg-781',
          productDescription: 'SOLVENT FREE EPOXY GAL.781 LIGHT GREY',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
      ],
    },
    {
      id: 5,
      categoryID: 'special-paint',
      categoryName: 'SPECIAL PAINT',
      categoryDescription: '',
      categoryImage: '',
      subCategories: [],
      products: [
        {
          id: 1,
          productID: 'baca',
          productName: 'BACA',
          productCode: 'TNT-BACAg-500',
          productDescription: 'BACA DECORATIVE BASE 500',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 2,
          productID: 'baca',
          productName: 'BACA',
          productCode: 'TNT-BACAg-507',
          productDescription: 'BACA DECORATIVE BASE 507',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 3,
          productID: 'baca',
          productName: 'BACA',
          productCode: 'TNT-BACAg-510',
          productDescription: 'BACA DECORATIVE BASE 510',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 4,
          productID: 'decortek',
          productName: 'DECORTEK',
          productCode: 'TNT-DECORTEKg-800',
          productDescription: 'DECORTEK DECORATIVE BASE 800',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 5,
          productID: 'smartmatch-1232',
          productName: 'SMARTMATCH 1232',
          productCode: 'TNT-EN-N-g',
          productDescription: 'ENAMEL GALLON NEUTRAL',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 6,
          productID: 'smartmatch-1232',
          productName: 'SMARTMATCH 1232',
          productCode: 'TNT-EN-W0-g',
          productDescription: 'ENAMEL WHITE 0 GALLON',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 7,
          productID: 'smartmatch-1232',
          productName: 'SMARTMATCH 1232',
          productCode: 'TNT-EN-W1-g',
          productDescription: 'ENAMEL GALLON WHITE 1',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 8,
          productID: 'smartmatch-1232',
          productName: 'SMARTMATCH 1232',
          productCode: 'TNT-EN-W3-g',
          productDescription: 'ENAMEL GALLON WHITE 3',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 9,
          productID: 'floe',
          productName: 'FLOE',
          productCode: 'TNT-FLOEg-600',
          productDescription: 'FLOE DECORATIVE BASE 600',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 10,
          productID: 'floe',
          productName: 'FLOE',
          productCode: 'TNT-FLOEg-620',
          productDescription: 'FLOE DECORATIVE BASE 620',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 11,
          productID: 'floe',
          productName: 'FLOE',
          productCode: 'TNT-FLOEg-630',
          productDescription: 'FLOE DECORATIVE BASE 630',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 12,
          productID: 'smartmatch-1232',
          productName: 'SMARTMATCH 1232',
          productCode: 'TNT-GAL',
          productDescription: 'TNT MISC.GALLON',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 13,
          productID: 'smartmatch-1232',
          productName: 'SMARTMATCH 1232',
          productCode: 'TNT-SLX-N-5g',
          productDescription: 'TNT SUPER LATEX BASE NEUTRAL',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 14,
          productID: 'smartmatch-1232',
          productName: 'SMARTMATCH 1232',
          productCode: 'TNT-SLX-N-g',
          productDescription: 'TNT SUPER LATEX BASE NEUTRAL',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 15,
          productID: 'smartmatch-1232',
          productName: 'SMARTMATCH 1232',
          productCode: 'TNT-SLX-W0-5g',
          productDescription: 'TNT SUPER LATEX BASE W0 BKT',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 16,
          productID: 'smartmatch-1232',
          productName: 'SMARTMATCH 1232',
          productCode: 'TNT-SLX-W0-g',
          productDescription: 'TNT SUPER LATEX BASE W0 GAL.',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 17,
          productID: 'smartmatch-1232',
          productName: 'SMARTMATCH 1232',
          productCode: 'TNT-SLX-W1-5g',
          productDescription: 'TNT SUPER LATEX BASE W1 BKT',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 18,
          productID: 'smartmatch-1232',
          productName: 'SMARTMATCH 1232',
          productCode: 'TNT-SLX-W1-g',
          productDescription: 'TNT SUPER LATEX BASE W1 GAL',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 19,
          productID: 'smartmatch-1232',
          productName: 'SMARTMATCH 1232',
          productCode: 'TNT-SLX-W3-5g',
          productDescription: 'TNT SUPER LATEX BASE W3 BKT',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 20,
          productID: 'smartmatch-1232',
          productName: 'SMARTMATCH 1232',
          productCode: 'TNT-SLX-W3-g',
          productDescription: 'TNT SUPER LATEX BASE W3 GAL',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
      ],
    },
    {
      id: 6,
      categoryID: 'thinner-other-solvents',
      categoryName: 'THINNER & OTHER SOLVENTS',
      categoryDescription: '',
      categoryImage: '',
      subCategories: [],
      products: [
        {
          id: 1,
          productID: 'paint-remover',
          productName: 'PAINT REMOVER',
          productCode: 'NPI-PRg',
          productDescription: 'PAINT REMOVER GALLON',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 2,
          productID: 'paint-remover',
          productName: 'PAINT REMOVER',
          productCode: 'NPI-PRq',
          productDescription: 'PAINT REMOVER QUARTS',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 3,
          productID: 'general-purpose-thinner',
          productName: 'GENERAL PURPOSE THINNER',
          productCode: 'NPI-TH GP5L',
          productDescription: 'GEN PURP THINNER 5L',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 4,
          productID: 'general-purpose-thinner',
          productName: 'GENERAL PURPOSE THINNER',
          productCode: 'NPI-TH GPg',
          productDescription: 'GEN PURP THINNER GAL.',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 5,
          productID: 'general-purpose-thinner',
          productName: 'GENERAL PURPOSE THINNER',
          productCode: 'NPI-TH GPq',
          productDescription: 'GEN PURP THINNER QRT.',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 6,
          productID: 'nc-lacquer-thinner',
          productName: 'NC LACQUER THINNER',
          productCode: 'NPI-TH NC5L',
          productDescription: 'NC LAQUER THINNER 5L',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 7,
          productID: 'nc-lacquer-thinner',
          productName: 'NC LACQUER THINNER',
          productCode: 'NPI-THg',
          productDescription: 'NC LAQUER THINNER GAL.',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 8,
          productID: 'nc-lacquer-thinner',
          productName: 'NC LACQUER THINNER',
          productCode: 'NPI-THq',
          productDescription: 'NC LACQUER THINNER QT.',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 9,
          productID: 'white-spirit',
          productName: 'WHITE SPIRIT',
          productCode: 'NPI-WSg',
          productDescription: 'WHITE SPIRIT',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 10,
          productID: 'white-spirit',
          productName: 'WHITE SPIRIT',
          productCode: 'NPI-WSq',
          productDescription: 'WHITE SPIRIT QT.',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
      ],
    },
    {
      id: 7,
      categoryID: 'solvent-based-paint',
      categoryName: 'SOLVENT BASED PAINT',
      categoryDescription: '',
      categoryImage: '',
      subCategories: [],
      products: [
        {
          id: 1,
          productID: 'super-traffic-paint',
          productName: 'SUPER TRAFFIC PAINT',
          productCode: 'NPI-STRPg-100',
          productDescription: 'SUPER TRAFFIC PAINT WHITE 100',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 2,
          productID: 'super-traffic-paint',
          productName: 'SUPER TRAFFIC PAINT',
          productCode: 'NPI-STRPg-120',
          productDescription: 'SUPER TRAFFIC PAINT YELLOW 120',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 3,
          productID: 'super-traffic-paint',
          productName: 'SUPER TRAFFIC PAINT',
          productCode: 'NPI-STRPg-123',
          productDescription: 'SUPER TRAFFIC PAINT RED 123',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 4,
          productID: 'super-traffic-paint',
          productName: 'SUPER TRAFFIC PAINT',
          productCode: 'NPI-STRPg-135',
          productDescription: 'SUPER TRAFFIC PAINT BLACK 135',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
      ],
    },
    {
      id: 8,
      categoryID: 'water-paint',
      categoryName: 'WATER PAINT',
      categoryDescription: '',
      categoryImage: '',
      subCategories: [],
      products: [
        {
          id: 1,
          productID: 'contractor-grade',
          productName: 'CONTRACTOR GRADE',
          productCode: 'NPI-CGd-200',
          productDescription: 'CG EMULSION BUCKET.200 WHITE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 2,
          productID: 'contractor-grade',
          productName: 'CONTRACTOR GRADE',
          productCode: 'NPI-CGd-201',
          productDescription: 'CG EMULSION BUCKET.201 OFF WHITE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 3,
          productID: 'contractor-grade',
          productName: 'CONTRACTOR GRADE',
          productCode: 'NPI-CGd-202',
          productDescription: 'CG EMULSION BUCKET.202 IVORY',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 4,
          productID: 'contractor-grade',
          productName: 'CONTRACTOR GRADE',
          productCode: 'NPI-CGd-203',
          productDescription: 'CG EMULSION BUCKET.203 CREAM',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 5,
          productID: 'contractor-grade',
          productName: 'CONTRACTOR GRADE',
          productCode: 'NPI-CGdm-200',
          productDescription: 'CGD MEDIUM-200 WHITE 3.5 USG',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 6,
          productID: 'contractor-grade',
          productName: 'CONTRACTOR GRADE',
          productCode: 'NPI-CGdm-201',
          productDescription: 'CGD MEDIUM-201 OFF WHITE 3.5 USG',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 7,
          productID: 'contractor-grade',
          productName: 'CONTRACTOR GRADE',
          productCode: 'NPI-CGdm-202',
          productDescription: 'CGD MEDIUM-202 IVORY 3.5 USG',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 8,
          productID: 'contractor-grade',
          productName: 'CONTRACTOR GRADE',
          productCode: 'NPI-CGdm-203',
          productDescription: 'CGD MEDIUM-203 CREAM 3.5 USG',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 9,
          productID: 'contractor-grade',
          productName: 'CONTRACTOR GRADE',
          productCode: 'NPI-CGg-200',
          productDescription: 'CG GALLON.200 WHITE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 10,
          productID: 'contractor-grade',
          productName: 'CONTRACTOR GRADE',
          productCode: 'NPI-CGg-201',
          productDescription: 'CG GALLON.201 OFF WHITE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 11,
          productID: 'contractor-grade',
          productName: 'CONTRACTOR GRADE',
          productCode: 'NPI-CGg-202',
          productDescription: 'CG GALLON.202 IVORY',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 12,
          productID: 'contractor-grade',
          productName: 'CONTRACTOR GRADE',
          productCode: 'NPI-CGg-203',
          productDescription: 'CG GALLON.203 CREAM',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 13,
          productID: 'floortex',
          productName: 'FLOORTEX',
          productCode: 'NPI-FPg-500',
          productDescription: 'FLOORTEX GAL.500 BRICK RED',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 14,
          productID: 'floortex',
          productName: 'FLOORTEX',
          productCode: 'NPI-FPg-510',
          productDescription: 'FLOORTEX GAL.510 GREY',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 15,
          productID: 'floortex',
          productName: 'FLOORTEX',
          productCode: 'NPI-FPg-520',
          productDescription: 'FLOORTEX GAL.520 GREEN',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 16,
          productID: 'floortex',
          productName: 'FLOORTEX',
          productCode: 'NPI-FPg-IT 170-6',
          productDescription: 'FLOORTEX GAL.IT 170-6',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 17,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-200',
          productDescription: 'LATEX EMULSION BKT.200 WHITE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 18,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-201',
          productDescription: 'LATEX EMULSION BKT.201 OFF WHITE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 19,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-202',
          productDescription: 'LATEX EMULSION BKT.202 IVORY',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 20,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-203',
          productDescription: 'LATEX EMULSION BKT.203 CREAM',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 21,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-209',
          productDescription: 'LATEX EMULSION BKT.209 BEIGE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 22,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-210',
          productDescription: 'LATEX EMULSION BKT.210 S.DUNE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 23,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-211',
          productDescription: 'LATEX EMULSION BKT.211 SUEDE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 24,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-212',
          productDescription: 'LATEX EMULSION BKT.212 PEACH',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 25,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-213',
          productDescription: 'LATEX EMULSION BKT.213 FLAMINGO',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 26,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-219',
          productDescription: 'LATEX EMULSION BKT.219 LEM YELLOW',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 27,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-220',
          productDescription: 'LATEX EMULSION BKT.220 YELLOW',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 28,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-222',
          productDescription: 'LATEX EMULSION BKT.222 MAIZE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 29,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-223',
          productDescription: 'LATEX EMULSION BKT.223 JAVA TOUCH',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 30,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-225',
          productDescription: 'LATEX EMULSION BKT.225 TAN',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 31,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-226',
          productDescription: 'LATEX EMULSION BKT.226 SALMON',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 32,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-227',
          productDescription: 'LATEX EMULSION BKT.227 RED',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 33,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-228',
          productDescription: 'LATEX EMULSION BKT.228 ROSE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 34,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-229',
          productDescription: 'LATEX EMULSION BKT.229 ORANGE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 35,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-230',
          productDescription: 'LATEX EMULSION BKT.230 L.GREY',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 36,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-231',
          productDescription: 'LATEX EMULSION BKT.231 D.GREY',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 37,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-232',
          productDescription: 'LATEX EMULSION BKT.232 S.GREY',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 38,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-233',
          productDescription: 'LATEX EMULSION BKT.233 BLUE GREY',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 39,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-234',
          productDescription: 'LATEX EMULSION BKT.234 PURPLE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 40,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-235',
          productDescription: 'LATEX EMULSION BKT.235 ROYAL FUSIA',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 41,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-240',
          productDescription: 'LATEX EMULSION BKT.240 L.BLUE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 42,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-241',
          productDescription: 'LATEX EMULSION BKT.241 C.BLUE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 43,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-242',
          productDescription: 'LATEX EMULSION BKT.242 D.BLUE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 44,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-243',
          productDescription: 'LATEX EMULSION BKT.243 S.TURQ',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 45,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-244',
          productDescription: 'LATEX EMULSION BKT.244 BALI BLUE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 46,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-250',
          productDescription: 'LATEX EMULSION BKT.250 L.GREEN',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 47,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-251',
          productDescription: 'LATEX EMULSION BKT.251 B.GREEN',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 48,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-252',
          productDescription: 'LATEX EMULSION BKT.252 LEMON',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 49,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-253',
          productDescription: 'LATEX EMULSION BKT.253 S.GREEN',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 50,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-254',
          productDescription: 'LATEX EMULSION BKT.254 O.GREEN',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 51,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-255',
          productDescription: 'LATEX EMULSION BKT.255 CRISP GREEN',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 52,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-256',
          productDescription: 'LATEX EMULSION BKT.256 PISTACHIO',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 53,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-258',
          productDescription: 'LATEX EMULSION BKT.258 PICKLE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 54,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-260',
          productDescription: 'LATEX EMULSION BKT.260 SCARLET',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 55,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-261',
          productDescription: 'LATEX EMULSION BKT.261 BAKED CLAY',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 56,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-262',
          productDescription: 'LATEX EMULSION BKT.262 CABB. ROSE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 57,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEd-270',
          productDescription: 'LATEX EMULSION BKT.270 COFFEE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['large', 'medium'],
        },
        {
          id: 58,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-200',
          productDescription: 'LATEX EMULSION GAL.200 WHITE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 59,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-201',
          productDescription: 'LATEX EMULSION GAL.201 OFF WHITE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 60,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-202',
          productDescription: 'LATEX EMULSION GAL.202 IVORY',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 61,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-203',
          productDescription: 'LATEX EMULSION GAL.203 CREAM',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 62,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-209',
          productDescription: 'LATEX EMULSION GAL.209 BEIGE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 63,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-210',
          productDescription: 'LATEX EMULSION GAL.210 S.DUNE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 64,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-211',
          productDescription: 'LATEX EMULSION GAL.211 SUEDE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 65,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-212',
          productDescription: 'LATEX EMULSION GAL.212 PEACH',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 66,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-213',
          productDescription: 'LATEX EMULSION GAL.213 FLAMING',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 67,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-219',
          productDescription: 'LATEX EMULSION GAL.219 LEMON YEL',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 68,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-220',
          productDescription: 'LATEX EMULSION GAL.220 LIGHT YEL',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 69,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-222',
          productDescription: 'LATEX EMULSION GAL.222 MAIZE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 70,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-223',
          productDescription: 'LATEX EMULSION GAL.223 JAVA TOUCH',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 71,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-225',
          productDescription: 'LATEX EMULSION GAL.225 TAN',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 72,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-226',
          productDescription: 'LATEX EMULSION GAL.226 SALMON',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 73,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-227',
          productDescription: 'LATEX EMULSION GAL.227 RED',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 74,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-228',
          productDescription: 'LATEX EMULSION GAL.228 ROSE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 75,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-229',
          productDescription: 'LATEX EMULSION GAL.229 ORANGE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 76,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-230',
          productDescription: 'LATEX EMULSION GAL.230 L.GRAY',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 77,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-231',
          productDescription: 'LATEX EMULSION GAL.231 D.GRAY',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 78,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-232',
          productDescription: 'LATEX EMULSION GAL.232 S.GRAY',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 79,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-233',
          productDescription: 'LATEX EMULSION GAL.233 BLUE GREY',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 80,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-234',
          productDescription: 'LATEX EMULSION GAL.234 PURPLE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 81,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-235',
          productDescription: 'LATEX EMULSION GAL.235 ROYAL FUSIA',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 82,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-239',
          productDescription: 'LATEX EMULSION GAL.239 AQUA',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 83,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-240',
          productDescription: 'LATEX EMULSION GAL.240 L.BLUE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 84,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-241',
          productDescription: 'LATEX EMULSION GAL.241 CAR.BLUE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 85,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-242',
          productDescription: 'LATEX EMULSION GAL.242 DEEP BLUE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 86,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-243',
          productDescription: 'LATEX EMULSION GAL.243 SP.TURQ',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 87,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-244',
          productDescription: 'LATEX EMULSION GAL.244 BALI BLUE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 88,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-250',
          productDescription: 'LATEX EMULSION GAL.250 L.GREEN',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 89,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-251',
          productDescription: 'LATEX EMULSION GAL.251 B.GREEN',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 90,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-252',
          productDescription: 'LATEX EMULSION GAL.252 L.GREEN',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 91,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-253',
          productDescription: 'LATEX EMULSION GAL.253 S.GREEN',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 92,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-254',
          productDescription: 'LATEX EMULSION GAL.254 O.GREEN',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 93,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-255',
          productDescription: 'LATEX EMULSION GAL.255 CRISP GREEN',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 94,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-256',
          productDescription: 'LATEX EMULSION GAL.256 PISTACHIO',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 95,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-258',
          productDescription: 'LATEX EMULSION GAL.258 PICKLE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 96,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-260',
          productDescription: 'LATEX EMULSION GAL.260 SCARLET',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 97,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-261',
          productDescription: 'LATEX EMULSION GAL.261 BAKED CLAY',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 98,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-262',
          productDescription: 'LATEX EMULSION GAL.262 CABB. ROSE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 99,
          productID: 'latex-emulsion',
          productName: 'LATEX EMULSION',
          productCode: 'NPI-LEg-270',
          productDescription: 'LATEX EMULSION GAL.270 COFFEE',
          productImage: '',
          productColor: ['black', 'grey'],
          prodductSize: ['gallon'],
        },
        {
          id: 100,
          productID: 'rolltex',
          productName: 'ROLLTEX',
          productCode: 'NPI-RTd-200',
          productDescription: 'ROLLTEX WHITE.200 G1/2',
          productImage: '',
          productColor: ['white'],
          prodductSize: ['bucket', 'gallon'],
        },
        {
          id: 101,
          productID: 'rolltex',
          productName: 'ROLLTEX',
          productCode: 'NPI-RTd-200-G3',
          productDescription: 'ROLLTEX WHITE.200 G3',
          productImage: '',
          productColor: ['white'],
          prodductSize: ['bucket', 'gallon'],
        },
        {
          id: 102,
          productID: 'rolltex',
          productName: 'ROLLTEX',
          productCode: 'NPI-RTd-201',
          productDescription: 'ROLLTEX OFF-WHITE.201 G1/2',
          productImage: '',
          productColor: ['off-white'],
          prodductSize: ['bucket', 'gallon'],
        },
        {
          id: 103,
          productID: 'rolltex',
          productName: 'ROLLTEX',
          productCode: 'NPI-RTd-202',
          productDescription: 'ROLLTEX IVORY.202 G1/2',
          productImage: '',
          productColor: ['ivory'],
          prodductSize: ['bucket', 'gallon'],
        },
        {
          id: 104,
          productID: 'rolltex',
          productName: 'ROLLTEX',
          productCode: 'NPI-RTd-232',
          productDescription: 'ROLLTEX SMOKE GREY.232 G1/2',
          productImage: '',
          productColor: ['grey'],
          prodductSize: ['bucket', 'gallon'],
        },
        {
          id: 105,
          productID: 'rolltex',
          productName: 'ROLLTEX',
          productCode: 'NPI-RTd-260',
          productDescription: 'ROLLTEX SCARLET.260 G1/2',
          productImage: '',
          productColor: ['red'],
          prodductSize: ['bucket', 'gallon'],
        },
        {
          id: 106,
          productID: 'weathercoat',
          productName: 'WEATHERCOAT',
          productCode: 'NPI-SILKd-160-2',
          productDescription: 'WC ACRYLIC BKT.160-2 DARK BLUE',
          productImage: '',
          productColor: ['dark blue'],
          prodductSize: ['bucket'],
        },
        {
          id: 107,
          productID: 'weathercoat',
          productName: 'WEATHERCOAT',
          productCode: 'NPI-SILKd-200',
          productDescription: 'WC ACRYLIC BKT.200 WHITE',
          productImage: '',
          productColor: ['white'],
          prodductSize: ['bucket'],
        },
        {
          id: 108,
          productID: 'weathercoat',
          productName: 'WEATHERCOAT',
          productCode: 'NPI-SILKd-201',
          productDescription: 'WC ACRYLIC BKT.201 OFF WHITE',
          productImage: '',
          productColor: ['off-white'],
          prodductSize: ['bucket'],
        },
        {
          id: 109,
          productID: 'weathercoat',
          productName: 'WEATHERCOAT',
          productCode: 'NPI-SILKd-202',
          productDescription: 'WC ACRYLIC BKT.202 IVORY',
          productImage: '',
          productColor: ['ivory'],
          prodductSize: ['bucket'],
        },
        {
          id: 110,
          productID: 'weathercoat',
          productName: 'WEATHERCOAT',
          productCode: 'NPI-SILKd-203',
          productDescription: 'WC ACRYLIC BKT.203 CREAM',
          productImage: '',
          productColor: ['cream'],
          prodductSize: ['bucket'],
        },
        {
          id: 111,
          productID: 'weathercoat',
          productName: 'WEATHERCOAT',
          productCode: 'NPI-SILKd-210',
          productDescription: 'WC ACRYLIC BKT.210 SAND DUNE',
          productImage: '',
          productColor: ['sand dune'],
          prodductSize: ['bucket'],
        },
        {
          id: 112,
          productID: 'weathercoat',
          productName: 'WEATHERCOAT',
          productCode: 'NPI-SILKd-211',
          productDescription: 'WC ACRYLIC BKT.211 SUEDE',
          productImage: '',
          productColor: ['suede'],
          prodductSize: ['bucket'],
        },
        {
          id: 113,
          productID: 'weathercoat',
          productName: 'WEATHERCOAT',
          productCode: 'NPI-SILKd-223',
          productDescription: 'WC ACRYLIC BKT.223 JAVA TOUCH',
          productImage: '',
          productColor: ['java touch'],
          prodductSize: ['bucket'],
        },
        {
          id: 114,
          productID: 'weathercoat',
          productName: 'WEATHERCOAT',
          productCode: 'NPI-SILKd-225',
          productDescription: 'WC ACRYLIC BKT.225 TAN',
          productImage: '',
          productColor: ['tan'],
          prodductSize: ['bucket'],
        },
        {
          id: 115,
          productID: 'weathercoat',
          productName: 'WEATHERCOAT',
          productCode: 'NPI-SILKd-228',
          productDescription: 'WC ACRYLIC BKT.228 ROSE',
          productImage: '',
          productColor: ['rose'],
          prodductSize: ['bucket'],
        },
        {
          id: 116,
          productID: 'weathercoat',
          productName: 'WEATHERCOAT',
          productCode: 'NPI-SILKd-229',
          productDescription: 'WC ACRYLIC BKT.229 ORANGE',
          productImage: '',
          productColor: ['orange'],
          prodductSize: ['bucket'],
        },
        {
          id: 117,
          productID: 'weathercoat',
          productName: 'WEATHERCOAT',
          productCode: 'NPI-SILKd-230',
          productDescription: 'WC ACRYLIC BKT.230 LIGHT GREY',
          productImage: '',
          productColor: ['light grey'],
          prodductSize: ['bucket'],
        },
        {
          id: 118,
          productID: 'weathercoat',
          productName: 'WEATHERCOAT',
          productCode: 'NPI-SILKd-231',
          productDescription: 'WC ACRYLIC BKT.231 DARK GREY',
          productImage: '',
          productColor: ['dark grey'],
          prodductSize: ['bucket'],
        },
        {
          id: 119,
          productID: 'weathercoat',
          productName: 'WEATHERCOAT',
          productCode: 'NPI-SILKd-232',
          productDescription: 'WC ACRYLIC BKT.232 SMOKE GREY',
          productImage: '',
          productColor: ['smoke grey'],
          prodductSize: ['bucket'],
        },
        {
          id: 120,
          productID: 'weathercoat',
          productName: 'WEATHERCOAT',
          productCode: 'NPI-SILKd-233',
          productDescription: 'WC ACRYLIC BKT.233 BLUE GREY',
          productImage: '',
          productColor: ['blue grey'],
          prodductSize: ['bucket'],
        },
        {
          id: 121,
          productID: 'weathercoat',
          productName: 'WEATHERCOAT',
          productCode: 'NPI-SILKd-240',
          productDescription: 'WC ACRYLIC BKT.240 LIGHT BLUE',
          productImage: '',
          productColor: ['light blue'],
          prodductSize: ['bucket'],
        },
        {
          id: 122,
          productID: 'weathercoat',
          productName: 'WEATHERCOAT',
          productCode: 'NPI-SILKd-245',
          productDescription: 'WC ACRYLIC BKT.245 DARK BLUE',
          productImage: '',
          productColor: ['dark blue'],
          prodductSize: ['bucket'],
        },
        {
          id: 123,
          productID: 'weathercoat',
          productName: 'WEATHERCOAT',
          productCode: 'NPI-SILKd-257',
          productDescription: 'WC ACRYLIC BKT.257 LUCKY GREEN',
          productImage: '',
          productColor: ['lucky green'],
          prodductSize: ['bucket'],
        },
        {
          id: 124,
          productID: 'weathercoat',
          productName: 'WEATHERCOAT',
          productCode: 'NPI-SILKd-260',
          productDescription: 'WC ACRYLIC BKT.260 SCARLET',
          productImage: '',
          productColor: ['scarlet'],
          prodductSize: ['bucket'],
        },
        {
          id: 125,
          productID: 'weathercoat',
          productName: 'WEATHERCOAT',
          productCode: 'NPI-SILKd-262',
          productDescription: 'WC ACRYLIC BKT.262 CABBAGE ROSE',
          productImage: '',
          productColor: ['cabbage rose'],
          prodductSize: ['bucket'],
        },
        {
          id: 126,
          productID: 'weathercoat',
          productName: 'WEATHERCOAT',
          productCode: 'NPI-SILKd-270',
          productDescription: 'WC ACRYLIC BKT.270 COFFEE',
          productImage: '',
          productColor: ['coffee'],
          prodductSize: ['bucket'],
        },
        {
          id: 127,
          productID: 'weathercoat',
          productName: 'WEATHERCOAT',
          productCode: 'NPI-SILKd-NEUTRAL',
          productDescription: 'WC EMULSION BKT NEUTRAL',
          productImage: '',
          productColor: ['neutral'],
          prodductSize: ['bucket'],
        },
        {
          id: 128,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-200',
          productDescription: 'SLE BKT.200 WHITE',
          productImage: '',
          productColor: ['white'],
          prodductSize: ['bucket'],
        },
        {
          id: 129,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-201',
          productDescription: 'SLE BKT.201 OFF WHITE',
          productImage: '',
          productColor: ['off-white'],
          prodductSize: ['bucket'],
        },
        {
          id: 130,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-202',
          productDescription: 'SLE BKT.202 IVORY',
          productImage: '',
          productColor: ['ivory'],
          prodductSize: ['bucket'],
        },
        {
          id: 131,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-203',
          productDescription: 'SLE BKT.203 CREAM',
          productImage: '',
          productColor: ['cream'],
          prodductSize: ['bucket'],
        },
        {
          id: 132,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-209',
          productDescription: 'SLE BKT.209 BEIGE',
          productImage: '',
          productColor: ['beige'],
          prodductSize: ['bucket'],
        },
        {
          id: 133,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-210',
          productDescription: 'SLE BKT.210 SAND DUNE',
          productImage: '',
          productColor: ['sand dune'],
          prodductSize: ['bucket'],
        },
        {
          id: 134,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-211',
          productDescription: 'SLE BKT.211 SUEDE',
          productImage: '',
          productColor: ['suede'],
          prodductSize: ['bucket'],
        },
        {
          id: 135,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-212',
          productDescription: 'SLE BKT.212 PEACH',
          productImage: '',
          productColor: ['peach'],
          prodductSize: ['bucket'],
        },
        {
          id: 136,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-213',
          productDescription: 'SLE BKT.213 FLAMINGO',
          productImage: '',
          productColor: ['flamingo'],
          prodductSize: ['bucket'],
        },
        {
          id: 137,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-219',
          productDescription: 'SLE BKT.219 LEMON YELLOW',
          productImage: '',
          productColor: ['yellow'],
          prodductSize: ['bucket'],
        },
        {
          id: 138,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-220',
          productDescription: 'SLE BKT.220 LIGHT YELLOW',
          productImage: '',
          productColor: ['light yellow'],
          prodductSize: ['bucket'],
        },
        {
          id: 139,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-222',
          productDescription: 'SLE BKT.222 MAIZE',
          productImage: '',
          productColor: ['maize'],
          prodductSize: ['bucket'],
        },
        {
          id: 140,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-223',
          productDescription: 'SLE BKT.223 JAVA TOUCH',
          productImage: '',
          productColor: ['java touch'],
          prodductSize: ['bucket'],
        },
        {
          id: 141,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-225',
          productDescription: 'SLE BKT.225 TAN',
          productImage: '',
          productColor: ['tan'],
          prodductSize: ['bucket'],
        },
        {
          id: 142,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-226',
          productDescription: 'SLE BKT.226 SALMON',
          productImage: '',
          productColor: ['salmon'],
          prodductSize: ['bucket'],
        },
        {
          id: 143,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-227',
          productDescription: 'SLE BKT.227 RED',
          productImage: '',
          productColor: ['red'],
          prodductSize: ['bucket'],
        },
        {
          id: 144,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-228',
          productDescription: 'SLE BKT.228 ROSE',
          productImage: '',
          productColor: ['rose'],
          prodductSize: ['bucket'],
        },
        {
          id: 145,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-229',
          productDescription: 'SLE BKT.229 ORANGE',
          productImage: '',
          productColor: ['orange'],
          prodductSize: ['bucket'],
        },
        {
          id: 146,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-230',
          productDescription: 'SLE BKT.230 LIGHT GREY',
          productImage: '',
          productColor: ['light grey'],
          prodductSize: ['bucket'],
        },
        {
          id: 147,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-231',
          productDescription: 'SLE BKT.231 DARK GREY',
          productImage: '',
          productColor: ['dark grey'],
          prodductSize: ['bucket'],
        },
        {
          id: 148,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-232',
          productDescription: 'SLE BKT.232 SMOKE GREY',
          productImage: '',
          productColor: ['smoke grey'],
          prodductSize: ['bucket'],
        },
        {
          id: 149,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-233',
          productDescription: 'SLE BKT.233 BLUE GREY',
          productImage: '',
          productColor: ['blue grey'],
          prodductSize: ['bucket'],
        },
        {
          id: 150,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-234',
          productDescription: 'SLE BKT.234 PURPLE',
          productImage: '',
          productColor: ['purple'],
          prodductSize: ['bucket'],
        },
        {
          id: 151,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-240',
          productDescription: 'SLE BKT.240 LIGHT BLUE',
          productImage: '',
          productColor: ['light blue'],
          prodductSize: ['bucket'],
        },
        {
          id: 152,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-241',
          productDescription: 'SLE BKT.241 CARIBBEAN BLUE',
          productImage: '',
          productColor: ['caribbean blue'],
          prodductSize: ['bucket'],
        },
        {
          id: 153,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-242',
          productDescription: 'SLE BKT.242 DEEP BLUE',
          productImage: '',
          productColor: ['deep blue'],
          prodductSize: ['bucket'],
        },
        {
          id: 154,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-243',
          productDescription: 'SLE BKT.243 SPLASHY TURQUOISE',
          productImage: '',
          productColor: ['turquoise'],
          prodductSize: ['bucket'],
        },
        {
          id: 155,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-244',
          productDescription: 'SLE BKT.244 BALI BLUE',
          productImage: '',
          productColor: ['bali blue'],
          prodductSize: ['bucket'],
        },
        {
          id: 156,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-250',
          productDescription: 'SLE BKT.250 LIGHT GREEN',
          productImage: '',
          productColor: ['light green'],
          prodductSize: ['bucket'],
        },
        {
          id: 157,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-251',
          productDescription: 'SLE BKT.251 BRIGHT GREEN',
          productImage: '',
          productColor: ['bright green'],
          prodductSize: ['bucket'],
        },
        {
          id: 158,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-252',
          productDescription: 'SLE BKT.252 LEMON GREEN',
          productImage: '',
          productColor: ['lemon green'],
          prodductSize: ['bucket'],
        },
        {
          id: 159,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-253',
          productDescription: 'SLE BKT.253 SURF GREEN',
          productImage: '',
          productColor: ['surf green'],
          prodductSize: ['bucket'],
        },
        {
          id: 160,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-254',
          productDescription: 'SLE BKT.254 OLIVE GREEN',
          productImage: '',
          productColor: ['olive green'],
          prodductSize: ['bucket'],
        },
        {
          id: 161,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-258',
          productDescription: 'SLE BKT.258 PICKLE',
          productImage: '',
          productColor: ['pickle'],
          prodductSize: ['bucket'],
        },
        {
          id: 162,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-260',
          productDescription: 'SLE BKT.260 SCARLET',
          productImage: '',
          productColor: ['scarlet'],
          prodductSize: ['bucket'],
        },
        {
          id: 163,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-261',
          productDescription: 'SLE BKT.261 BAKED CLAY',
          productImage: '',
          productColor: ['baked clay'],
          prodductSize: ['bucket'],
        },
        {
          id: 164,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-262',
          productDescription: 'SLE BKT.262 CABBAGE ROSE',
          productImage: '',
          productColor: ['cabbage rose'],
          prodductSize: ['bucket'],
        },
        {
          id: 165,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEd-270',
          productDescription: 'SLE BKT.270 COFFEE',
          productImage: '',
          productColor: ['coffee'],
          prodductSize: ['bucket'],
        },
        {
          id: 166,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEg-200',
          productDescription: 'SLE GALLON 200 WHITE',
          productImage: '',
          productColor: ['white'],
          prodductSize: ['gallon'],
        },
        {
          id: 167,
          productID: 'super-latex-emulsion',
          productName: 'SUPER LATEX EMULSION',
          productCode: 'NPI-SLEg-BLACK',
          productDescription: 'SLE GALLON BLACK',
          productImage: '',
          productColor: ['black'],
          prodductSize: ['gallon'],
        },
        {
          id: 168,
          productID: 'water-based-sealer',
          productName: 'WATER BASED SEALER',
          productCode: 'NPI-WBS-CLEAR',
          productDescription: 'WATER BASED SEALER CLEAR',
          productImage: '',
          productColor: ['clear'],
          prodductSize: ['bucket'],
        },
        {
          id: 169,
          productID: 'water-based-sealer',
          productName: 'WATER BASED SEALER',
          productCode: 'NPI-WBS-WHITE',
          productDescription: 'WATER BASED SEALER WHITE',
          productImage: '',
          productColor: ['white'],
          prodductSize: ['bucket'],
        },
        {
          id: 170,
          productID: 'water-proofing-paint',
          productName: 'WATER PROOFING PAINT',
          productCode: 'NPI-WPd-WHITE',
          productDescription: 'WATER PROOFING BKT. WHITE',
          productImage: '',
          productColor: ['white'],
          prodductSize: ['bucket'],
        },
        {
          id: 171,
          productID: 'water-proofing-paint',
          productName: 'WATER PROOFING PAINT',
          productCode: 'NPI-WPmd-WHITE',
          productDescription: 'WATER PROOFING MBKT. WHITE',
          productImage: '',
          productColor: ['white'],
          prodductSize: ['medium bucket'],
        },
        {
          id: 172,
          productID: 'paint-remover',
          productName: 'PAINT REMOVER',
          productCode: 'NPI-PRg',
          productDescription: 'PAINT REMOVER GALLON',
          productImage: '',
          productColor: ['clear'],
          prodductSize: ['gallon'],
        },
        {
          id: 173,
          productID: 'paint-remover',
          productName: 'PAINT REMOVER',
          productCode: 'NPI-PRq',
          productDescription: 'PAINT REMOVER QUARTS',
          productImage: '',
          productColor: ['clear'],
          prodductSize: ['quart'],
        },
        {
          id: 174,
          productID: 'general-purpose-thinner',
          productName: 'GENERAL PURPOSE THINNER',
          productCode: 'NPI-TH GP5L',
          productDescription: 'GEN PURP THINNER 5L',
          productImage: '',
          productColor: ['clear'],
          prodductSize: ['5L'],
        },
        {
          id: 175,
          productID: 'general-purpose-thinner',
          productName: 'GENERAL PURPOSE THINNER',
          productCode: 'NPI-TH GPg',
          productDescription: 'GEN PURP THINNER GAL.',
          productImage: '',
          productColor: ['clear'],
          prodductSize: ['gallon'],
        },
        {
          id: 176,
          productID: 'general-purpose-thinner',
          productName: 'GENERAL PURPOSE THINNER',
          productCode: 'NPI-TH GPq',
          productDescription: 'GEN PURP THINNER QRT.',
          productImage: '',
          productColor: ['clear'],
          prodductSize: ['quart'],
        },
        {
          id: 177,
          productID: 'nc-lacquer-thinner',
          productName: 'NC LACQUER THINNER',
          productCode: 'NPI-TH NC5L',
          productDescription: 'NC LAQUER THINNER 5L',
          productImage: '',
          productColor: ['clear'],
          prodductSize: ['5L'],
        },
        {
          id: 178,
          productID: 'nc-lacquer-thinner',
          productName: 'NC LACQUER THINNER',
          productCode: 'NPI-THg',
          productDescription: 'NC LAQUER THINNER GAL.',
          productImage: '',
          productColor: ['clear'],
          prodductSize: ['gallon'],
        },
        {
          id: 179,
          productID: 'nc-lacquer-thinner',
          productName: 'NC LACQUER THINNER',
          productCode: 'NPI-THq',
          productDescription: 'NC LACQUER THINNER QT.',
          productImage: '',
          productColor: ['clear'],
          prodductSize: ['quart'],
        },
        {
          id: 180,
          productID: 'white-spirit',
          productName: 'WHITE SPIRIT',
          productCode: 'NPI-WSg',
          productDescription: 'WHITE SPIRIT',
          productImage: '',
          productColor: ['clear'],
          prodductSize: ['gallon'],
        },
        {
          id: 181,
          productID: 'white-spirit',
          productName: 'WHITE SPIRIT',
          productCode: 'NPI-WSq',
          productDescription: 'WHITE SPIRIT QT.',
          productImage: '',
          productColor: ['clear'],
          prodductSize: ['quart'],
        },
        {
          id: 182,
          productID: 'super-traffic-paint',
          productName: 'SUPER TRAFFIC PAINT',
          productCode: 'NPI-STRPg-100',
          productDescription: 'SUPER TRAFFIC PAINT WHITE 100',
          productImage: '',
          productColor: ['white'],
          prodductSize: ['gallon'],
        },
        {
          id: 183,
          productID: 'super-traffic-paint',
          productName: 'SUPER TRAFFIC PAINT',
          productCode: 'NPI-STRPg-120',
          productDescription: 'SUPER TRAFFIC PAINT YELLOW 120',
          productImage: '',
          productColor: ['yellow'],
          prodductSize: ['gallon'],
        },
        {
          id: 184,
          productID: 'super-traffic-paint',
          productName: 'SUPER TRAFFIC PAINT',
          productCode: 'NPI-STRPg-123',
          productDescription: 'SUPER TRAFFIC PAINT RED 123',
          productImage: '',
          productColor: ['red'],
          prodductSize: ['gallon'],
        },
        {
          id: 185,
          productID: 'super-traffic-paint',
          productName: 'SUPER TRAFFIC PAINT',
          productCode: 'NPI-STRPg-135',
          productDescription: 'SUPER TRAFFIC PAINT BLACK 135',
          productImage: '',
          productColor: ['black'],
          prodductSize: ['gallon'],
        },
        {
          id: 186,
          productID: 'baca',
          productName: 'BACA',
          productCode: 'TNT-BACAg-500',
          productDescription: 'BACA DECORATIVE BASE 500',
          productImage: '',
          productColor: ['neutral'],
          prodductSize: ['gallon'],
        },
        {
          id: 187,
          productID: 'baca',
          productName: 'BACA',
          productCode: 'TNT-BACAg-507',
          productDescription: 'BACA DECORATIVE BASE 507',
          productImage: '',
          productColor: ['neutral'],
          prodductSize: ['gallon'],
        },
        {
          id: 188,
          productID: 'baca',
          productName: 'BACA',
          productCode: 'TNT-BACAg-510',
          productDescription: 'BACA DECORATIVE BASE 510',
          productImage: '',
          productColor: ['neutral'],
          prodductSize: ['gallon'],
        },
        {
          id: 189,
          productID: 'decortek',
          productName: 'DECORTEK',
          productCode: 'TNT-DECORTEKg-800',
          productDescription: 'DECORTEK DECORATIVE BASE 800',
          productImage: '',
          productColor: ['neutral'],
          prodductSize: ['gallon'],
        },
        {
          id: 190,
          productID: 'smartmatch-1232',
          productName: 'SMARTMATCH 1232',
          productCode: 'TNT-EN-N-g',
          productDescription: 'ENAMEL GALLON NEUTRAL',
          productImage: '',
          productColor: ['neutral'],
          prodductSize: ['gallon'],
        },
        {
          id: 191,
          productID: 'smartmatch-1232',
          productName: 'SMARTMATCH 1232',
          productCode: 'TNT-EN-W0-g',
          productDescription: 'ENAMEL WHITE 0 GALLON',
          productImage: '',
          productColor: ['white'],
          prodductSize: ['gallon'],
        },
        {
          id: 192,
          productID: 'smartmatch-1232',
          productName: 'SMARTMATCH 1232',
          productCode: 'TNT-EN-W1-g',
          productDescription: 'ENAMEL GALLON WHITE 1',
          productImage: '',
          productColor: ['white'],
          prodductSize: ['gallon'],
        },
        {
          id: 193,
          productID: 'smartmatch-1232',
          productName: 'SMARTMATCH 1232',
          productCode: 'TNT-EN-W3-g',
          productDescription: 'ENAMEL GALLON WHITE 3',
          productImage: '',
          productColor: ['white'],
          prodductSize: ['gallon'],
        },
        {
          id: 194,
          productID: 'floe',
          productName: 'FLOE',
          productCode: 'TNT-FLOEg-600',
          productDescription: 'FLOE DECORATIVE BASE 600',
          productImage: '',
          productColor: ['neutral'],
          prodductSize: ['gallon'],
        },
        {
          id: 195,
          productID: 'floe',
          productName: 'FLOE',
          productCode: 'TNT-FLOEg-620',
          productDescription: 'FLOE DECORATIVE BASE 620',
          productImage: '',
          productColor: ['neutral'],
          prodductSize: ['gallon'],
        },
        {
          id: 196,
          productID: 'floe',
          productName: 'FLOE',
          productCode: 'TNT-FLOEg-630',
          productDescription: 'FLOE DECORATIVE BASE 630',
          productImage: '',
          productColor: ['neutral'],
          prodductSize: ['gallon'],
        },
        {
          id: 197,
          productID: 'smartmatch-1232',
          productName: 'SMARTMATCH 1232',
          productCode: 'TNT-GAL',
          productDescription: 'TNT MISC. GALLON',
          productImage: '',
          productColor: ['neutral'],
          prodductSize: ['gallon'],
        },
        {
          id: 198,
          productID: 'smartmatch-1232',
          productName: 'SMARTMATCH 1232',
          productCode: 'TNT-SLX-N-5g',
          productDescription: 'TNT SUPER LATEX BASE NEUTRAL',
          productImage: '',
          productColor: ['neutral'],
          prodductSize: ['5 gallon'],
        },
        {
          id: 199,
          productID: 'smartmatch-1232',
          productName: 'SMARTMATCH 1232',
          productCode: 'TNT-SLX-N-g',
          productDescription: 'TNT SUPER LATEX BASE NEUTRAL',
          productImage: '',
          productColor: ['neutral'],
          prodductSize: ['gallon'],
        },
        {
          id: 200,
          productID: 'smartmatch-1232',
          productName: 'SMARTMATCH 1232',
          productCode: 'TNT-SLX-W0-5g',
          productDescription: 'TNT SUPER LATEX BASE W0 BKT',
          productImage: '',
          productColor: ['W0'],
          prodductSize: ['5 gallon'],
        },
        {
          id: 201,
          productID: 'smartmatch-1232',
          productName: 'SMARTMATCH 1232',
          productCode: 'TNT-SLX-W0-g',
          productDescription: 'TNT SUPER LATEX BASE W0 GAL.',
          productImage: '',
          productColor: ['W0'],
          prodductSize: ['gallon'],
        },
        {
          id: 202,
          productID: 'smartmatch-1232',
          productName: 'SMARTMATCH 1232',
          productCode: 'TNT-SLX-W1-5g',
          productDescription: 'TNT SUPER LATEX BASE W1 BKT',
          productImage: '',
          productColor: ['W1'],
          prodductSize: ['5 gallon'],
        },
        {
          id: 203,
          productID: 'smartmatch-1232',
          productName: 'SMARTMATCH 1232',
          productCode: 'TNT-SLX-W1-g',
          productDescription: 'TNT SUPER LATEX BASE W1 GAL',
          productImage: '',
          productColor: ['W1'],
          prodductSize: ['gallon'],
        },
        {
          id: 204,
          productID: 'smartmatch-1232',
          productName: 'SMARTMATCH 1232',
          productCode: 'TNT-SLX-W3-5g',
          productDescription: 'TNT SUPER LATEX BASE W3 BKT',
          productImage: '',
          productColor: ['W3'],
          prodductSize: ['5 gallon'],
        },
        {
          id: 205,
          productID: 'smartmatch-1232',
          productName: 'SMARTMATCH 1232',
          productCode: 'TNT-SLX-W3-g',
          productDescription: 'TNT SUPER LATEX BASE W3 GAL',
          productImage: '',
          productColor: ['W3'],
          prodductSize: ['gallon'],
        },
      ],
    },
    {
      id: 9,
      categoryID: 'wood',
      categoryName: 'WOOD',
      categoryDescription: '',
      categoryImage: '',
      subCategories: [],
      products: [
        {
          id: 0,
          productID: '1k-polyurethane-varnish',
          productName: '1K POLYURETHANE VARNISH',
          productCode: 'NPI-1KPUg-350',
          productDescription: '1K POLYURETHANE VARNISH GAL. CLEAR',
          productImage: '',
          productColor: ['clear'],
          prodductSize: ['gallon'],
        },
        {
          id: 1,
          productID: '1k-polyurethane-varnish',
          productName: '1K POLYURETHANE VARNISH',
          productCode: 'NPI-1KPUg-360',
          productDescription: '1K POLYURETHANE VARNISH GAL. MAHOGANY',
          productImage: '',
          productColor: ['mahogany'],
          prodductSize: ['gallon'],
        },
        {
          id: 2,
          productID: 'wood-lacquer',
          productName: 'WOOD LACQUER',
          productCode: 'NPI-LGd',
          productDescription: 'CLEAR WOOD LACQUER BKT',
          productImage: '',
          productColor: ['clear'],
          prodductSize: ['bucket'],
        },
        {
          id: 3,
          productID: 'wood-lacquer',
          productName: 'WOOD LACQUER',
          productCode: 'NPI-LGg',
          productDescription: 'CLEAR WOOD LACQUER GAL',
          productImage: '',
          productColor: ['clear'],
          prodductSize: ['gallon'],
        },
        {
          id: 4,
          productID: 'wood-lacquer',
          productName: 'WOOD LACQUER',
          productCode: 'NPI-LGg(50%)',
          productDescription: 'CLEAR WOOD LACQUER SEMI GLOSS',
          productImage: '',
          productColor: ['semi-gloss'],
          prodductSize: ['gallon'],
        },
        {
          id: 5,
          productID: 'wood-lacquer',
          productName: 'WOOD LACQUER',
          productCode: 'NPI-LGg-MATT',
          productDescription: 'WOOD LACQUER GAL MATT',
          productImage: '',
          productColor: ['matt'],
          prodductSize: ['gallon'],
        },
        {
          id: 6,
          productID: 'wood-sealer',
          productName: 'WOOD SEALER',
          productCode: 'NPI-LSd',
          productDescription: 'WOOD SEALER BUCKET',
          productImage: '',
          productColor: ['clear'],
          prodductSize: ['bucket'],
        },
        {
          id: 7,
          productID: 'wood-sealer',
          productName: 'WOOD SEALER',
          productCode: 'NPI-LSg',
          productDescription: 'WOOD SEALER GALLON',
          productImage: '',
          productColor: ['clear'],
          prodductSize: ['gallon'],
        },
        {
          id: 8,
          productID: 'alkyd-varnish',
          productName: 'ALKYD VARNISH',
          productCode: 'NPI-VAd-300',
          productDescription: 'VARNISH BUCKET CLEAR',
          productImage: '',
          productColor: ['clear'],
          prodductSize: ['bucket'],
        },
        {
          id: 9,
          productID: 'alkyd-varnish',
          productName: 'ALKYD VARNISH',
          productCode: 'NPI-VAd-310',
          productDescription: 'VARNISH BUCKET MAHOGANY',
          productImage: '',
          productColor: ['mahogany'],
          prodductSize: ['bucket'],
        },
        {
          id: 10,
          productID: 'alkyd-varnish',
          productName: 'ALKYD VARNISH',
          productCode: 'NPI-VAg-300',
          productDescription: 'VARNISH GAL.CLEAR',
          productImage: '',
          productColor: ['clear'],
          prodductSize: ['gallon'],
        },
        {
          id: 11,
          productID: 'alkyd-varnish',
          productName: 'ALKYD VARNISH',
          productCode: 'NPI-VAg-310',
          productDescription: 'VARNISH GAL.MAHOGANY',
          productImage: '',
          productColor: ['mahogany'],
          prodductSize: ['gallon'],
        },
        {
          id: 12,
          productID: 'alkyd-varnish',
          productName: 'ALKYD VARNISH',
          productCode: 'NPI-VAg-320',
          productDescription: 'VARNISH GAL.WALNUT',
          productImage: '',
          productColor: ['walnut'],
          prodductSize: ['gallon'],
        },
        {
          id: 13,
          productID: 'alkyd-varnish',
          productName: 'ALKYD VARNISH',
          productCode: 'NPI-VAq-300',
          productDescription: 'VARNISH QT.CLEAR',
          productImage: '',
          productColor: ['clear'],
          prodductSize: ['quart'],
        },
        {
          id: 14,
          productID: 'alkyd-varnish',
          productName: 'ALKYD VARNISH',
          productCode: 'NPI-VAq-310',
          productDescription: 'VARNISH QT.MAHOGANY',
          productImage: '',
          productColor: ['mahogany'],
          prodductSize: ['quart'],
        },
        {
          id: 15,
          productID: 'wood-stain',
          productName: 'WOOD STAIN',
          productCode: 'NPI-WST1LCHERRY',
          productDescription: 'WOOD STAIN CHERRY RED 1L',
          productImage: '',
          productColor: ['cherry red'],
          prodductSize: ['1L'],
        },
        {
          id: 16,
          productID: 'wood-stain',
          productName: 'WOOD STAIN',
          productCode: 'NPI-WST1LMAHOGANY',
          productDescription: 'WOOD STAIN MAHOGANY 1L',
          productImage: '',
          productColor: ['mahogany'],
          prodductSize: ['1L'],
        },
      ],
    },
  ],
}));
